version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend
    restart: always
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: ./app.py
    ports: ['5000:5000']
    volumes: ['./backend:/app']
    depends_on:
      - mongo
    networks:
      - backend
  
  mongo:
    image: mongo:4.0.8
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - backend
    volumes:
      - ./mongo:/docker-entrypoint-initdb.d
  
  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    volumes: 
      - ./frontend:/src
      - /src/node_modules
      - /src/.next
    ports:
      - "3000:3000"

networks:
  backend:
    driver: bridge
