version: '3.8'

services:
  backend:
    build: ./backend
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: ./app.py
    ports: ['5000:5000']
    volumes: ['./backend:/app']

  frontend:
    build: ./frontend
    restart: always
    ports:
      - 3000:3000